version: "3.3"

services:

  hello:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: hello_service
    ports:
      - 5002:80
    volumes:
      - "./app:/app"
    restart: unless-stopped
